# 1. 리스트와 함께 사용하는 함수
* sorted():정렬
* min(): 최소값을 구해주는 함수
* max(): 최대값을 구해주는 함수
* sum(): 더해주는 함수

리스트에 가장 큰 수 찾기 max()

In [1]:
a = [38, 21, 53, 62, 19]

a 리스트에서 가장 큰 수만 출력해 주세요.

In [6]:
temp = a[0]
for i in a:
  if temp <=i:
    temp = i
print(temp)

62


In [7]:
max(a)

62

In [9]:
sorted(a)[-1]

62

In [12]:
sorted(a, reverse=True)[0]

62

19

리스트에서 가장 작은 수 찾기 min()

In [14]:
min(a)

19

In [16]:
sorted(a)[0]

19

리스트 내의 값을 모두 더해 합계 구하기

In [17]:
a

[38, 21, 53, 62, 19]

In [20]:
hap = 0
for i in a:
  hap += i
print(hap, end=" ")

193 

In [19]:
sum(a)

193

# 2. 리스트 표현식(list comprehension) 사용하기

* list 안에 for 반복문과 if else 조건식을 한 번에 적는 방법
* 다소 복잡해 보일 수 있지만, 여러 줄의 코드를 1줄로 줄일 수 있고, for, if else 문을 쓸 때 보다 처리 속도가 빠르다.

```
[식 for 변수 in list]
```

In [21]:
# 0부터 9까지 숫자를 생성하여 리스트 생성
L = []
for i in range(1, 10):
  L.append(i)
L

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
참 if 조건식 else 거짓


In [22]:
# list 표현식으로 1-9 리스트 만들기
a = [i for i in range(1, 11)]
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

리스트 표현식을 써야하는 이유

In [26]:
%%timeit
a = []
for i in range(1, 100000000):
  a.append(i + 5)
print(a[0:10])

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
13.8 s ± 904 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%%timeit

b = [i + 5 for i in range(1,100000000)]
print(b[0:10])

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
9.04 s ± 584 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%%timeit
import numpy as np

i = np.arange(1, 100000000)
print(type(i))
c = i + 5
print(c[0:10])

<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
<class 'numpy.ndarray'>
[ 6  7  8  9 10 11 12 13 14 15]
525 ms ± 34.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 파일 읽기, 파일쓰기
* open()
* with open()

## 1) open()
* 파일에 문자열을 쓰거나 읽을 때는 open 함수로 파일을 열어서 write메서드를 사용해 저장
```
변수명 = open("파일이름", 파일모드(w,r,bw, br)
변수명.write("저장할 내용")
변수명.close()
```
close로 꼭 파일을 닫아 주어야 함.

파일 만들고 내용 저장하기

In [32]:
file = open('test.txt', 'w')
file.write("파일 만들기 연습 입니다.")
file.close()

만든 파일 읽어오기: 옵션만 w => r
```
변수1 = open("읽어올 파일명", 'r')
변수2 = 변수1.read()
변수1.close()
```

In [33]:
file2 = open('test.txt', 'r')
my_file = file2.read()
file2.close()
print(my_file)

파일 만들기 연습 입니다.


## with문으로 파일 자동으로 닫기

In [34]:
with open('test_with.txt', 'w') as file3:
  file3.write("with open을 사용하면 파일을 자동으로 닫아주어 편리하다.")

In [35]:
with open('test_with.txt', 'r') as file4:
  my_file2 = file4.read()
print(my_file2)

with open을 사용하면 파일을 자동으로 닫아주어 편리하다.


# 파일을 읽어서 반복문과 리스트로 자료 처리하기

* readlines() 파일을 한 줄씩 읽어와서 list로 변경해 줌.

In [43]:
with open("/content/drive/MyDrive/Colab Notebooks/datas/hotels_info.csv", 'r') as file:
          data = file.readlines()

In [ ]:
data

In [45]:
print(type(data))

<class 'list'>


In [46]:
len(data)

10001

In [47]:
data[0]

',hotelId,hotelName,tripType,tripTypeText,reviewDate,rating,description,isKorNot\n'

In [48]:
data[1]

'356,105343,서울 웨스틴조선호텔 (The Westin Chosun Seoul),family,1박 가족 여행,2019년 1월 26일,10.0,직원들 서비스나 마인드 완벽합니다 다만 노후된 시설과 좁은 라운지가 호텔 이름에 비해 약간 부족합니다,True\n'

In [53]:
temp = data[1]

In [56]:
temp2 = temp.split(",")

In [62]:
temp2

['356',
 '105343',
 '서울 웨스틴조선호텔 (The Westin Chosun Seoul)',
 'family',
 '1박 가족 여행',
 '2019년 1월 26일',
 '10.0',
 '직원들 서비스나 마인드 완벽합니다 다만 노후된 시설과 좁은 라운지가 호텔 이름에 비해 약간 부족합니다',
 'True\n']

In [59]:
hotel_name = temp2[2]

In [61]:
review_contents = temp2[7:]

In [78]:
hotels = []
review_text = []
for review in data:
  # print(review)
  temp2 = review.split(",")
  hotel_name = temp2[2]
  review_contents = temp2[7:]
  print(hotel_name)
  print(review_contents)
  hotels.append(hotel_name)
  review_text.append(review_contents)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['놀라운 뷰에 안락한 잠자리 맛있는조식', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['깨끗하고 직원들은 요청사항들을 친절히 잘 처리해주셨습니다대체적으로 만족스런 가족여행이었고 재방문 의사있습니다', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['아주 좋았어요 밤에 쉐라톤 포차도 좋았어요', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['침구에 아주 만족했습니다', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['수영장이 오픈안해서 수영장땜에 간건데 너무 아쉬웠어요', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['여자친구와 첫 호캉스였는데 너무나 만족했습니다서비스면 서비스 청결이면 청결특히 체크인 해주셨던분들이 너무 친절했어요위치도 센트럴파크 바로앞이라 너무 좋았습니다', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['방이 큰편이라 좋아요 주변이 조용했고 센트럴파크뷰 너무 좋았습니다직원분들도 굉장히 친절하시고 서비스 잘 해주세요', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['서비스와 시설에 만족합니다', 'True\n']
쉐라톤 그랜드 인천 호텔 (Sheraton Grand Incheon Hotel)
['호텔스닷컴 통해 3인으로 검색 후 예약하고 갔습니다조식 2인이라 1인 추가결제는 이용평 보고 미리 알고 갔는데 체크인 과정에서 결제 완료 후 추가 1인 요금지불은 당황스럽더군요 엘리베이터 기다리는 시간이 길어서 불편했습니다룸컨디션

In [75]:
len(hotels)

1

In [77]:
hotels[0]

'서울 웨스틴조선호텔 (The Westin Chosun Seoul)'

In [65]:
len(review_text)

10001

In [69]:
review_text[999]

['2호선타고 입구 찾기가 쉽지 않았습니다만 전체적으로 만족합니다', 'True\n']