In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical
from numpy import array

In [51]:
import pandas as pd

In [54]:
sample = pd.DataFrame({'text': ['해보지', '않으면', '해낼', '수', '없다']})

In [55]:
sample

text
0  해보지
1  않으면
2   해낼
3    수
4   없다

In [56]:
pd.get_dummies(sample)

text_수  text_않으면  text_없다  text_해낼  text_해보지
0       0         0        0        0         1
1       0         1        0        0         0
2       0         0        0        1         0
3       1         0        0        0         0
4       0         0        1        0         0

In [33]:
text = '해보지 않으면 해낼 수 없다.'

In [34]:
result = text_to_word_sequence(text)
print("원문: ", text)
print("토큰화: ", result) #토큰, 코퍼스(corpus)

원문:  해보지 않으면 해낼 수 없다.
토큰화:  ['해보지', '않으면', '해낼', '수', '없다']


In [35]:
# 단어 빈도수 세기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

# 토크나이저 사용법

In [36]:
# 문장 토큰화 하기
token = Tokenizer(lower=False)
token.fit_on_texts(docs)

In [37]:
print('단어 카운트: ', token.word_counts)

단어 카운트:  OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [38]:
print('문장 카운트:', token.document_count)

문장 카운트: 3


In [39]:
print('각 단어가 몇 개의 문장에 포함되어 있는가? ', token.word_docs)

각 단어가 몇 개의 문장에 포함되어 있는가?  defaultdict(<class 'int'>, {'각': 1, '토큰화': 1, '나누어': 1, '합니다': 1, '먼저': 1, '텍스트의': 2, '단어를': 1, '단어로': 1, '토큰화해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '결과는': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '사용할': 1})


In [40]:
print('각 단어에 매겨진 인덱스:', token.word_index)

각 단어에 매겨진 인덱스: {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


# 단어의 원-핫 인코딩

In [41]:
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'
token = Tokenizer(lower=False)
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [42]:
# 단어를 벡터로 변환
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [43]:
len(token.word_index)

6

In [44]:
# 인덱스에 1을 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1

In [45]:
x = to_categorical(x, num_classes=word_size)
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 텍스트를 읽고 긍정, 부정 예측하기

In [46]:
docs = ["너무 재밌네요", "최고예요", "참 잘 만든 영화예요", "추천하고 싶은 영화입니다.", "한번 더 보고싶네요",
        "글쎄요", "별로예요", "생각보다 지루하네요", "연기가 어색해요", "재미없어요"]

# 긍정 리뷰는 1, 부정리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [47]:
# 토큰화
token = Tokenizer(lower=False)
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [48]:
token.word_counts

OrderedDict([('너무', 1),
             ('재밌네요', 1),
             ('최고예요', 1),
             ('참', 1),
             ('잘', 1),
             ('만든', 1),
             ('영화예요', 1),
             ('추천하고', 1),
             ('싶은', 1),
             ('영화입니다', 1),
             ('한번', 1),
             ('더', 1),
             ('보고싶네요', 1),
             ('글쎄요', 1),
             ('별로예요', 1),
             ('생각보다', 1),
             ('지루하네요', 1),
             ('연기가', 1),
             ('어색해요', 1),
             ('재미없어요', 1)])

In [17]:
# 원핫인코딩
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [18]:
# 패딩 추가 pad_sequences(데이터, 가장 긴 문장의 길이)
padded_x = pad_sequences(x, 4)
print("패딩 결과", padded_x )

패딩 결과 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [19]:
type(padded_x )

numpy.ndarray

In [51]:
#임베딩에 입력된 단어의 수 지정
word_size = len(token.word_index) + 1

In [54]:
# 단어 임베딩을 포함해서 딥러닝 모델 생성
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) 
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [55]:
model.compile(loss= 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(padded_x, classes, epochs=20)
print('Accuracy: ', model.evaluate(padded_x, classes)[1])

Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 0.6942 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 22ms/step - loss: 0.6923 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 63ms/step - loss: 0.6904 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 33ms/step - loss: 0.6866 - accuracy: 0.6000
Epoch 6/20
1/1 [==============================] - 0s 14ms/step - loss: 0.6847 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6829 - accuracy: 0.8000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6810 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6791 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 16ms/step - loss: 0.6772 - accuracy: 0.9000
Epoch 11/20
1/1 [================